### ISSUE TITLE
Repository search doesn't work, "GraphqlResponseError"

### ISSUE THREAD

**Issue by neongreen** [microsoft/vscode-remote-repositories-github#133]
Issue Type: <b>Bug</b>

I have authenticated with GitHub but the "Open Remote Repository" search box doesn't show any repositories.

The console log says

```
[2022-02-23 11:55:18:539] /Users/artyom/.vscode/extensions/github.remotehub-0.25.2022022201/dist/extension.js:133:1102
GraphqlResponseError: Request failed due to following response errors:
 - Please contact int-index to resolve the issue.
```

I tried setting log level to debug, but this didn't help much:

```
[2022-02-23 11:55:16:923] [   11] (A) Reader(5|WorkspaceRepositories) • WorkspaceRepositories.get
[2022-02-23 11:55:16:924] [   11] (L) Reader(5|WorkspaceRepositories) waited for 0 ms • WorkspaceRepositories.get
[2022-02-23 11:55:16:924] [   11] (U) Reader(5|WorkspaceRepositories) locked for 0 ms • WorkspaceRepositories.get
[2022-02-23 11:55:18:539] /Users/artyom/.vscode/extensions/github.remotehub-0.25.2022022201/dist/extension.js:133:1102
GraphqlResponseError: Request failed due to following response errors:
 - Please contact int-index to resolve the issue.
```

`int-index` is the github nick of my frequent collaborator — there are orgs where we are co-owners, I have access to some of his repos, and he has access to some of my repos.

Extension version: 0.25.2022022301
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Connection to 'SSH: brick' could not be established  Canceled
Remote OS version: Linux x64 5.4.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id b9136842-338b-4ebd-856f-5fecbbbf24d3|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: brick' could not be established  Canceled

|Item|Value|
|---|---|
|Remote|SSH: brick-traefik|
|OS|Linux x64 5.4.0-97-generic|
|CPUs|DO-Regular (1 x 2199)|
|Memory (System)|0.95GB (0.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30442553
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by joyceerhl** [comment]
@neongreen Thanks for filing an issue and apologies for the inconvenience. That error appears to be coming from the GitHub GraphQL API. So that I can try to reproduce the error, how did you set up these orgs and repos? Do you have write permissions to those repos? Are the orgs SAML protected?

**Comment by neongreen** [comment]
@joyceerhl I've sent the output gist at your Microsoft email.

**Comment by joyceerhl** [comment]
Thank you--it looks like one of the repositories that you collaborate with `int-index` on is restricted by trade controls:

```
    "name": "GraphqlResponseError",
    "errors": [
        {
            "type": "TRADE_CONTROLS",
            "path": [
                "viewer",
                "repositories",
                "nodes",
                24
            ],
            "locations": [
                {
                    "line": 11,
                    "column": 7
                }
            ],
            "message": "Please contact int-index to resolve the issue."
        }
    ],
```

I have published a pre-release of RemoteHub which should display the remaining search results. Please give it a try in insiders.vscode.dev and let me know if you are able to search repositories now. Note that whichever repo triggered the error above will continue to not be displayed in the quickpick, as we have no way of knowing which repo it is.

**Comment by neongreen** [comment]
I opened insiders.vscode.dev and checked the GitHub Repositories version —
it's v0.25.2022022801.

Unfortunately I am still getting "Please contact int-index to resolve the
issue" and the repository search is still stuck.

**Comment by joyceerhl** [comment]
Thanks, I checked the gist you sent me again, and it looks like the response data contains a `null` that GitHub Repositories wasn't handling. I pushed a fix for this and published a new pre-release. Please give it a try and let me know if you still see issues. Thanks a lot for your patience!
