### ISSUE TITLE
Load merged PRs with deleted branches correctly

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#330]
Example:
https://github.com/microsoft/vscode/pull/180953

This PR is merged, and I can look at the diff on github.com just fine... but when I open it in vscode.dev I see:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/2644648/235806173-b90b73b7-e3f6-46bb-bc7d-5eec4b0c2e32.png">
and the branch is set to `main`:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/2644648/235806243-3b34979c-9030-4f67-9d79-170db6f48013.png">

and the PR experience doesn't start.

Since I'm able to see the diff just fine on github.com, I feel like I should be able to do similar on vscode.dev

cc @alexr00

**Comment by joyceerhl** [comment]
@alexr00 I fixed this in RemoteHub by using the name of the deleted branch in the workspace metadata (live in today's insiders). I'm also using the commit SHA corresponding to the merge commit for the PR. 

Do you foresee any unintended side effects from this in GHPRI? The only one I have found so far is that the sidebar text about checking out main without deleting the current branch may imply that the current branch still exists: 

![image](https://user-images.githubusercontent.com/30305945/235960526-a0c974a6-3c82-4fd0-be96-e2bed49dd2e4.png)

**Comment by alexr00** [comment]
@joyceerhl I think it should be fine. GHPRI hide PRs from the Pull Requests view if they don't have a remote branch, but they'll still show as the "active" PR if you're already on the branch.
