### ISSUE TITLE
Unable to find repository named ...

### ISSUE THREAD

**Issue by jeandersoncruz** [microsoft/vscode-remote-repositories-github#49]
Issue Type: <b>Bug</b>

Not being able to open any public repo at github.com when .git extension at the end of URL.
👎  https://github.com/microsoft/vscode-remote-repositories-github.git
👍🏼: https://github.com/microsoft/vscode-remote-repositories-github

Extension version: 0.13.3
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 7|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id a80e795f-f7bc-4354-b651-70c918cd6eff --crash-reporter-id a80e795f-f7bc-4354-b651-70c918cd6eff --crash-reporter-id a80e795f-f7bc-4354-b651-70c918cd6eff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30350415

```

</details>

**Comment by Jiunsr** [comment]
good issuce, thanks. I am also because this.
I hope the author solves it as soon as possible, otherwise many users may not use this plugin, thus lose users.

**Comment by ifendo** [comment]
Also want to report this issue on Win 10, Extension version: v0.13.4...

**Comment by eamodio** [comment]
This should be resolved in the latest extension version.

**Comment by Ruminateer** [comment]
@eamodio I am on v0.18.0 and I am still having this issue...

**Comment by joyceerhl** [comment]
@Ruminateer is this the dialog where you are entering the url that ends with .git, or is it a different place in the extension? 
![image](https://user-images.githubusercontent.com/30305945/145062763-3521099d-140d-4e8c-b2c2-09f83fbe82e0.png)

**Comment by Ruminateer** [comment]
@joyceerhl I selected "GitHub Repositories: Open Remote Repository..." in the command palette, and it looks exactly like the screenshot you posted.

**Comment by ifendo** [comment]
I got similiar issue today on win 10, v0.19.0
